steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  - name: gcr.io/cloud-builders/docker
    args: ["build","-t","asia-south1-docker.pkg.dev/kubedemo-412505/looksyou-docker/serviceregistry:v1","--build-arg=JAR_FILE=target/serviceregistry-0.0.1-SNAPSHOT.jar","."]
  - name: gcr.io/cloud-builders/docker
    args: ["push","asia-south1-docker.pkg.dev/kubedemo-412505/looksyou-docker/serviceregistry:v1"]
images: ["asia-south1-docker.pkg.dev/kubedemo-412505/looksyou-docker/serviceregistry:v1"]