steps:
  - name: maven:3.3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
artifacts:
  mavenArtifacts:
    - repository: https://asia-south1-maven.pkg.dev/kubedemo-412505/looksyou-repo
      path: ./workspace/target/
      groupId: com.looksyou
      artifactId: serviceregistry
      version: 0.0.1-SNAPSHOT